apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bataranetwork-pvc
  labels:
    app: bataranetwork
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
