{{- if .Values.networkPolicy.enabled -}}
# NetworkPolicy to restrict ingress traffic to the node pods.
# By default, it denies all ingress traffic and then explicitly allows
# connections on the HTTP and gRPC ports from any pod within the same namespace.
# This helps secure the node by preventing unwanted access from other namespaces.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "bataranetwork.name" . }}
  labels:
    {{- include "bataranetwork.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "bataranetwork.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Allow ingress traffic from any pod within the same namespace.
    # This is useful for allowing services like Prometheus or other microservices
    # within the same application stack to communicate with the node.
    - from:
      - podSelector: {} # An empty podSelector selects all pods in the namespace.
      ports:
        - protocol: TCP
          port: {{ .Values.service.httpPort }}
        - protocol: TCP
          port: {{ .Values.service.grpcPort }}
{{- end }}
