version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: explorer_frontend
    ports:
      - "5173:5173" # Vite dev server port
    volumes:
      - ./frontend:/app
      - /app/node_modules # Anonymous volume to prevent local node_modules from overwriting container's
    environment:
      - VITE_API_BASE_URL=http://localhost:4000

  backend:
    build:
      context: ./backend
    container_name: explorer_backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
